# ============================================================
#  FWS Linux — modules/users.conf
# ============================================================

# Nom d'hôte par défaut
defaultGroups:
  - users
  - lp
  - video
  - network
  - storage
  - wheel
  - audio
  - optical
  - scanner
  - power

# Autoriser le login automatique
autologinGroup:  autologin

# Sudoers — donne les droits sudo au groupe wheel
sudoersGroup:    wheel

# Shell par défaut pour les nouveaux utilisateurs
userShell:       /bin/bash

# Hostname par défaut
hostname:
  location:      EtcFile
  template:      "fws-${first}"

# Règles pour les mots de passe
passwordRequirements:
  minLength:     6
  maxLength:     -1
  nonempty:      true

# Permet de définir le même mot de passe pour root et user
allowWeakPasswords: false
