# ============================================================
#  FWS Linux — airootfs/etc/pacman.conf
# ============================================================

[options]
HoldPkg       = pacman glibc
Architecture  = auto

# Vérification des signatures
SigLevel      = Required DatabaseOptional
LocalFileSigLevel = Optional

# Couleurs dans le terminal
Color
ParallelDownloads = 5

# ============================================================
#  Dépôts officiels Arch
# ============================================================

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# ============================================================
#  Dépôt Arch Linux CN (pour Calamares AUR)
# ============================================================
[archlinuxcn]
Server = https://repo.archlinuxcn.org/$arch

# ============================================================
#  Dépôt FWS custom (optionnel — décommente si tu en as un)
# ============================================================
# [fws]
# SigLevel = Optional TrustAll
# Server = https://repo.fws-linux.org/$arch
