# ============================================================
#  FWS Linux — Calamares settings.conf
# ============================================================

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary

  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - initcpiocfg
    - initcpio
    - grubcfg
    - bootloader
    - umount

  - show:
    - finished

branding: fws

# Demande confirmation avant d'installer
prompt-install: true

# Ne pas chroot (laisser à false pour une install normale)
dont-chroot: false

# Désactive les vérifications réseau au démarrage
disable-cancel: false
disable-cancel-during-exec: true
