---
componentName: fws

strings:
  productName: FWS
  shortProductName: FWS
  version: 2026.03
  versionedName: FWS 2026.03
  bootloaderEntryName: FWS
  productUrl: https://github.com/ton-repo/fws
  supportUrl: https://github.com/ton-repo/fws/issues
  knownIssuesUrl: https://github.com/ton-repo/fws/issues
  releaseNotesUrl: https://github.com/ton-repo/fws

images:
  productLogo: logo.png
  productIcon: logo.png
  productWelcome: logo.png

slideshow: show.qml
slideshowAPI: 2