---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - initcpio
    - bootloader
    - services-systemd
    - umount
  - show:
    - finished

branding: default
prompt-install: false
dont-chroot: false
