# ============================================================
#  FWS Linux — modules/bootloader.conf
# ============================================================

# Bootloader à utiliser
# Options: grub, systemd-boot, refind
efiBootLoader:  "grub"

# Paramètres GRUB
grubInstall:    "grub-install"
grubMkconfig:   "grub-mkconfig"
grubCfg:        "baseline/grub/grub.cfg"

# Chemin EFI
efiDirectory:   "/boot/efi"

# ID pour l'entrée EFI
efiBootEntryName: "FWS Linux"

# Menu GRUB
grubTimeout:    5
grubQuiet:      false
