# ============================================================
#  FWS Linux — modules/finished.conf
# ============================================================

# Redémarrer automatiquement après l'installation
restartNowEnabled:  true
restartNowChecked:  false
restartNowCommand:  "systemctl reboot"

# Message de fin affiché à l'utilisateur
notifyOnFinished:   true
