# ============================================================
#  FWS Linux — modules/initcpiocfg.conf
#  Configure /etc/mkinitcpio.conf sur le système cible
# ============================================================

# Modules à inclure dans le initramfs
modules: []

# Binaires supplémentaires
binaries: []

# Fichiers supplémentaires
files: []

# Hooks — ordre important !
hooks:
  - base
  - udev
  - autodetect
  - modconf
  - block
  - filesystems
  - keyboard
  - fsck
