# ============================================================
#  FWS Linux — modules/unpackfs.conf
#  Copie le système live vers le disque cible
# ============================================================

unpack:
    # Source : le squashfs de l'ISO FWS
    # Adapte "FWS" selon la valeur de iso_name dans profiledef.sh
  - source: /run/archiso/bootmnt/FWS/x86_64/airootfs.sfs
    sourcefs: squashfs
    destination: ""

    # Alternative si tu utilises erofs au lieu de squashfs :
    # - source: /run/archiso/bootmnt/FWS/x86_64/airootfs.erofs
    #   sourcefs: erofs
    #   destination: ""
